# Setup
title:               Quazi
tagline:             'Computer Vision | AI | Machine Learning | LLM | AWS'
description:         ''
url:                 https://qmaruf.github.io
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Quazi Marufur Rahman
  url:               https://twitter.com/qmaruf
  email:             maruf.csdu@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
